const pay = async ({
      amount,
      cardNumber,
      cardCvv,
      cardExpirationMonth,
      cardExpirationYear,
      cardHolderCPF,
      cardHolderName,
      documentType,
      documentNumber,
      phoneAreaCode,
      phoneNumber,
      birthDate,
      senderName,
      items,
      senderEmail,
      street,
      number,
      // complement: "1",
      district,
      city,
      state,
      postalCode,
      pointOfSaleId,
      pointOfSaleToken,
 }) => {
    try {
        const response = await fetch(`https://painel.tahnamao.com.br/smartstore/pay`, {
          method: 'POST',
          body: {
            amount,
            cardNumber,
            cardCvv,
            items,
            cardExpirationMonth,
            cardExpirationYear,
            cardHolderCPF,
            cardHolderName,
            documentType,
            documentNumber,
            phoneAreaCode,
            phoneNumber,
            birthDate,
            senderName,
            senderEmail,
            street,
            number,
            // complement: "1",
            district,
            city,
            state,
            postalCode,
            pointOfSaleId,
            pointOfSaleToken,
          },
        });
      if (response.status !== 200) throw Error();
       return response;
    } catch (error) {
      console.warn('request error', JSON.stringify());
      console.warn({
        amount,
      cardNumber,
      cardCvv,
      cardExpirationMonth,
      cardExpirationYear,
      cardHolderCPF,
      cardHolderName,
      documentType,
      documentNumber,
      phoneAreaCode,
      phoneNumber,
      birthDate,
      senderName,
      items,
      senderEmail,
      street,
      number,
      // complement: "1",
      district,
      city,
      state,
      postalCode,
      pointOfSaleId,
      pointOfSaleToken,
      })
      throw error;
    } 
  }
  
  export default pay;